### ISSUE TITLE
Agrupar los datos del domicilio del odontólogo en un div 

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#12]
Hoy están separados
- calle
- número
- localidad

y está entremezclado con el campo Institución.

**Comment by alejandrosobko** [comment]
Acomodé los divs. No le gusta agruparlos.

**Comment by fdodino** [comment]
Volvimos a hablar de que lo que se pedía era hacer lo mismo que en la visita, un div que encierre los tres campos que se siguen cargando por separado. La idea es que cuando tengas 3 domicilios, no se entremezclen calle, calle2 y calle3, y después veas número, número 2, número 3 sino que se vayan trabajando en grupos de calle, número y localidad.

**Comment by alejandrosobko** [comment]
Hecho.
