### ISSUE TITLE
Cambiar look & feel de panel de Institución + Domiciliio

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#14]
Ver si se puede usar un panel-content
http://getbootstrap.com/components/#panels-basic

Y ver si se puede achicar algunos campos para que entre en menos líneas:

* Instituo
* Calle + Número
* Localidad

**Comment by alejandrosobko** [comment]
Hecho. También me pidieron que los horarios de atención sean parte del instituto y no uno general del odontólogo. Por lo tanto hice ese refactor y ahora los horarios de atención estan dentro del div de instituto.
No usé panels porque no quedaba bien, pero los pude dividir con un título y una fuente distinta.
