### ISSUE TITLE
Ultimas validaciones de WorkCalendar

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#15]
* Agregar un botón para limpiar el rango horario (si lo cargás lo deja, eso está ok, pero si te posicionás en otro día, queda cargado y te obliga a borrarlo manualmente). Además del +, que aparezca un botón Limpiar que borre el rango desde y hasta cargado. Puede ser un botón limpiar general o uno por día.
* Revisar que al cargar 1:30 quedó 1:30 y no 01:30 y eso ordenó incorrectamente los rangos.
* Mostrar un mensaje de error más representativo que diga : "En el día Lunes hay superposición de horarios" en lugar de "Horarios incorrectos"

**Comment by alejandrosobko** [comment]
Hecho.

- Agregué botón limpiar que borra todos los campos de los inputs
- Arreglé el problema de 1:30 que no quedaba 01:30 (fallaba por mezclar js pelado con Angualar :grin: )
- Agregué mensajes más representativos
