### ISSUE TITLE
Separar visualmente al odontólogo y al visitador en el CU Carga Odontólogo

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#4]
Que haya dos cards o divs/containers
http://getbootstrap.com/components/#panels

Para diferenciar los datos del odontólogo y los del visitador (incluso en la edición/visualización con el historial)

**Comment by alejandrosobko** [comment]
Lo hice usando tabs porque tener una página con tantos inputs se hacía molesto, sumado a tener que hacer scroll. Los cambios se pueden ver en master. Si no te gusta lo puedo cambiar.
