### ISSUE TITLE
Agregar validaciones mínimas en la carga de odontólogos

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#5]
* Que ingresen nombre y apellido del odontólogo
* Fecha de visita
* Nombre del visitador
* Que las validaciones de error salten por campo y no sean genéricas ("Algo salió mal" vs. "Debe ingresar fecha del día")

**Comment by alejandrosobko** [comment]
Hecho.

**Comment by fdodino** [comment]
Ok. Se cierra el issue.
