### ISSUE TITLE
Mejorar look & feel de búsqueda

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#6]
Agrandar un toque el campo que ingresa la búsqueda

Grilla, tener estas columnas
* Odontólogo
  (Nombre + " " + Apellido)
* Domicilio
  (Calle + Número en una línea + BR +
  Localidad + ( + Código Postal + )
* Datos de contacto
  Teléfono + BR +
  Link  MailTO: Mail (http://stackoverflow.com/questions/8794216/html5-tag-address-mailto-with-links)
* Especialidad
* (Horarios de atención quizás es mucho para una búsqueda)
* Agregar un tooltip / title para agregar una nueva visita y preguntar si le gusta a la derecha o a la izquierda

Usar well: http://getbootstrap.com/components/#wells

**Comment by alejandrosobko** [comment]
Hecho. Hice una combinación entre este pedido y la opinión del cliente.
