### ISSUE TITLE
Asociar la visita + los datos del odontólogo

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#7]
Hoy la nueva visita y cambiar datos del odontólogo están separados como CU.
Sería bueno unificarlos para poder asociarlos.
Hablar con la usuaria para ver qué opina  de esto.

**Comment by alejandrosobko** [comment]
Me dijo que son 2 cosas distintas. Por un lado hacen una visita, el odontólogo pudo haber cambiado o no sus datos, pero el objetivo de una visita no es ir a buscar sus nuevos datos, sino ir a llevarle nueva información, por eso tenemos el campo "Observations". 
Lo cierro.

**Comment by fdodino** [comment]
Ok.
