### ISSUE TITLE
Falta documentar entrega 1

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#8]
Visto en el checkpoint presencial previo a la entrega 2.

**Comment by fdodino** [comment]
Ok con la especificación de los casos de uso, falta el diagrama de casos de uso:
Leer https://docs.google.com/document/d/12DQ1ewTcr83WNEAOtckcoMPPdrmKb0gTqetR2EaxWF4/edit

**Comment by alejandrosobko** [comment]
Agregado el diagrama de casos de uso para la entrega 1, 2 y 3. Además agregué una nueva página con doc. de arquitectura actualizada luego de la 2° release.
