### ISSUE TITLE
Agregar validaciones de dominio a WorkCalendar

### ISSUE THREAD

**Issue by fdodino** [alejandrosobko/UNQ-TIP-Padron#9]
Evitar así que salgas del diálogo de carga de horarios si no está ok.

**Validaciones a agregar**
- Que no se superpongan los horarios
- Usar html5 con input = "time" y tratar de que no sea necesario ingresar PM/AM
- El botón + que aparezca al costado del hasta y que sea fácil de clickear (por ahí que sea botón)

**Comment by alejandrosobko** [comment]
Hice que no salgas del diálogo si hay errores, mejoré la vista y agregué unas validaciones. El botón con html5 funciona solo en chrome pero me rompe toda la vista para agregar el AM/PM que no aporta nada. Voy a agregar regex y alguna validación así armo algo parecido a mano..

**Comment by fdodino** [comment]
Ok con el primer avance, ahora faltaría

* validar que no se superpongan los horarios
* ordenar por horario desde para que aparezca más clara la presentación
* además ok con poner un regex, pero me parece mejor estas opciones
http://timepicker.co/
http://jonthornton.github.io/jquery-timepicker/

**Comment by alejandrosobko** [comment]
Listo.
* Usé http://timepicker.co/ para facilitar el ingreso de la hora
* Usé regex para validar el formato (client and server side)
* En el modelo ya no guardo un time (no necesito la fecha) sino que guardo un string con el formato que corresponde (HH:mm)
